---
title: "`r params$data` - CT COVID 19 Data"
author: "B. Gonzalez and S. Yraita, Jr"
date: "`r format.Date(Sys.time(), '%m/%d/%Y @ %H:%M:%S')`"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
params:
  data: "New London"
---

```{r setup, include=FALSE}
# include libraries
library(flexdashboard)
library(readr)
library(dplyr)
library(ggplot2)
library(knitr)

# get the data
covid <- read_csv("https://data.ct.gov/resource/bfnu-rgqt.csv")

# make sure data is in the right order
covid <- covid %>% arrange(dateupdated)

# Filters the data for a specified county, which is specified as a parameter 
# in the R Markdown file, and graphs the number of cases for this county ovr time.
covid_county <- covid %>% filter(county == params$data) 

# get date range
beginDate <- format.Date(first(covid$dateupdated), '%m/%d/%Y')
lastDate <- format.Date(last(covid$dateupdated), '%m/%d/%Y')
```

Row
-----------------------------------------------------------------------

### Total Number of cases

```{r}
cases <- last(covid_county$totalcases)
valueBox(cases, icon = "fa-folder-open")
```

### Total Number of deaths

```{r}
deaths <- last(covid_county$totaldeaths)
valueBox(deaths, icon = "fa-skull")
```

### Current Hospitalizations

```{r, echo=FALSE, message=FALSE}
hospitalizations <- last(covid_county$hospitalization)
if (hospitalizations > 20) {
  valueBox(hospitalizations, icon = "fa-first-aid", color = "danger")
} else if (hospitalizations > 10) {
  valueBox(hospitalizations, icon = "fa-first-aid", color = "warning")
} else {
  valueBox(hospitalizations, icon = "fa-first-aid", color = "primary")
}
```

Row {data-height=1000}
-----------------------------------------------------------------------
### Cases per Day

```{r, echo=FALSE, message=FALSE}
# Daily Cases along with its bar graph
cases1 <- covid_county$totalcases
daily_cases <- diff(cases1)
dc <- daily_cases < 0
daily_cases <- cbind(TotalCases = c(0,daily_cases))
df <- data.frame(daily_cases,covid_county$dateupdated)

barcases <- ggplot(data = df, aes(x=covid_county.dateupdated ,y = TotalCases, )) +
geom_bar(stat = "identity", fill="steelblue") + theme(legend.position = "none") + labs(x = " ", y = "Cases")

barcases
```


### Deaths per Day

```{r, echo=FALSE, message=FALSE}
# Daily deaths along with its bar graph
deaths1 <- covid_county$totaldeaths
daily_deaths <- diff(deaths1)
daily_deaths <- cbind(TotalDeaths = c(0,daily_deaths))
death_df <- data.frame(daily_deaths,covid_county$dateupdated)

bar_deaths <- ggplot(data = death_df, aes(x=covid_county.dateupdated ,y = TotalDeaths)) +
geom_bar(stat="identity", fill="black") + theme(legend.position = "none") + labs(x = " ", y = "Deaths")

bar_deaths
```

### Hospitalizations per Day

```{r, echo=FALSE, message=FALSE}
# Daily hospitilizations and its graph
bar_hospitilization <- ggplot(data = covid_county, aes(x = dateupdated , y = hospitalization)) +
geom_bar(stat="identity", fill="orange") + theme(legend.position = "none") + labs(x = " ", y = "Hospitalizations")

bar_hospitilization
```

Row
-----------------------------------------------------------------------

*This page contains COVID-19 information for `r params$data`, CT from `r beginDate ` to `r lastDate`.*