---
title: "CT Covid 19 Data"
author: "Brian Gonzalez and Sergio Yraita, Jr"
date: "`r format.Date(Sys.time(), '%m/%d/%Y @ %H:%M:%S')`"
output: html_document
---
```{r, echo=FALSE, message=FALSE}
# include libraries
library(readr)
library(dplyr)
library(ggplot2)
library(knitr)

# get the data
covid <- read_csv("https://data.ct.gov/resource/bfnu-rgqt.csv")

# make sure data is in the right order
covid <- covid %>% arrange(dateupdated)

# get date range
beginDate <- format.Date(first(covid$dateupdated), '%m/%d/%Y')
lastDate <- format.Date(last(covid$dateupdated), '%m/%d/%Y')
```


*This page contains COVID-19 information for CT, for the total number of cases from `r beginDate ` to `r lastDate`.*


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Total Cases Over Time

```{r, echo=FALSE, message=FALSE}
# Generates a graph of total cases over time for each county 
# plot cases over time
ggplot(covid, aes(dateupdated, totalcases, color = county)) +
  geom_line() + theme_classic() + xlab('')
```

## Most Recent Total Cases per County - Bar Graph

```{r, echo=FALSE, message=FALSE}
# Filters the data to look at only the most recent date
# and generates a bar graph of total cases per county
# covid_mr means covid most recent
lastDate <- last(covid$dateupdated)
covid_mr <- covid %>% filter(dateupdated == lastDate) 
colnames(covid_mr) <- c("Date Updated", "County Code", "County", 
                            "Total Cases", "Confirmed Cases", "Probable Cases",
                            "Total Case Rate", "Hospitalization", "Total Deaths",
                            "Confirmed Deaths", "Probable Deaths")

ggplot(data = covid_mr, aes(x= County, y = `Total Cases`, fill = County)) +
  geom_bar(stat = "identity") + ggtitle("Total Cases per County") +
  theme(legend.position = "none") + labs(x = "County", y = "Total Cases")
```

## Most Recent Total Cases per County - Table

```{r, echo=FALSE, message=FALSE}
# Display a table containing the data for the most recent date
covid_mr$`Date Updated` <- format.Date(covid_mr$`Date Updated`, '%m/%d/%Y')
kable(covid_mr[1:8, ], caption = "Recent Cases")
```

```{r, echo=FALSE, message=FALSE}



```